#!/usr/bin/env perl

use strict;
use warnings;

use 5.010;
use Carp;
use Net::Netmask;
use Socket;

INIT {
    croak 'You need to specify IP range' if $#ARGV < 0;

    foreach (@ARGV) {
        my $iprange = Net::Netmask->new($_);

        foreach ($iprange->enumerate) {
            my ($name) = gethostbyaddr inet_aton($_), AF_INET;
            say "$_: $name" if defined $name;
        }
    }
}

__END__
