#!/usr/bin/env perl

use strict;
use warnings;

use 5.010;
use AnyEvent;
use AnyEvent::DNS;
use Carp;
use Net::Netmask;

INIT {
    croak 'You need to specify IP range' if $#ARGV < 0;

    foreach (@ARGV) {
        my $iprange = Net::Netmask->new($_);

        my $cv = AnyEvent->condvar;
        $cv->begin;
        foreach my $ip ($iprange->enumerate) {
            $cv->begin;
            AnyEvent::DNS::reverse_lookup $ip, sub {
                my $names = join ', ', @_;
                say "$ip: $names" if $names;
                $cv->end;
            };
        }
        $cv->end;
        $cv->wait;
    }
}

__END__
